import { GameRoom } from "./game-room";

// Generated by `opennextjs-cloudflare build` before wrangler runs.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated worker does not exist until the preview/deploy build step.
import openNextWorker from "../../.open-next/worker.js";

interface EventGameEnv extends CloudflareEnv {
	GAME_ROOM: DurableObjectNamespace<GameRoom>;
	HOST_KEY?: string;
}

function getGameRoomStub(request: Request, env: EventGameEnv): DurableObjectStub<GameRoom> {
	const url = new URL(request.url);
	const gameId = url.pathname.split("/").filter(Boolean)[2] ?? "hall";
	const id = env.GAME_ROOM.idFromName(gameId);

	return env.GAME_ROOM.get(id);
}

export { GameRoom };

export default {
	fetch(request: Request, env: EventGameEnv, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);

		if (url.pathname.startsWith("/api/game/")) {
			return getGameRoomStub(request, env).fetch(request);
		}

		return openNextWorker.fetch(request, env, ctx);
	},
} satisfies ExportedHandler<EventGameEnv>;
